---
- name: Install Nautobot, Postgresql, Redis, Nginx,
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - postgresql
    - nginx
    - redis
    - nautobot